
## this script merges the multiple .csv in the folder with a common string in their name, by default "Results", this can be changed in the line 15


#Change the “path” variable to the folder where our .csv files generated by the Fiji macro are located.
#Example: path <- ("C:\\User\\script_segmentacion\\CSV\\CSV_batch\\")

path <- ("C:\\Users\\admin\\Desktop\\Proyectos\\script_segmentacion_2023\\script_segmentacion_2023\\CSV\\CSV_batch\\")

#Change the “csv_name” variable  to the desired final name of the .csv with all the cells of the group merged. (Example: “AFA123_total”)
#Example: csv_name <- "AFA123.csv"

csv_name <- "CSVMERGED.csv"

#Set the pattern value to the common string to all the desired CSV files.

pattern <- "Results"

files <- list.files(path, pattern = pattern)
total <- NULL

for (csv in files) {
  
  csv_cell <- paste0(as.character(path), as.character(csv))
  #this print the location and name of the merged .csv
  print (paste0(csv_cell," ","merged"))
  df <- read.csv(csv_cell)
  
  total <- rbind(total,df)
  
}


write.csv(total, paste0(path, csv_name), row.names = FALSE)

