
#Change the “path” variable to the folder where our .csv files generated by the Fiji macro are located.
#Example: path <- ("C:\\User\\script_segmentacion\\CSV\\CSV_batch\\")
path <- ("C:\\Users\\admin\\Desktop\\Proyectos\\script_segmentacion_2023\\script_segmentacion_2023\\CSV\\CSV_batch\\")

#Change the “var_label” value to the name that you want to associate to the cell group, by default the strain name. Example: var_label <- "AFA123"
var_label <- ""


setwd(path)
files <- list.files(path,pattern = "Results")


for (i in files){
  
  csv <- paste0(as.character(path),"", as.character(i))
  
  df <- read.csv(csv)
  
  
  frame_delete <- 0
  frame_delete <- df[grepl("[0-9]{4}-0002-[0-9]{4}", df$Label),][1,1]
  print(paste0("First frame deleted: ", frame_delete))
  if( !is.na(frame_delete) ){
    df<- df[-(frame_delete:4000),]
  }
  write.csv(df,i, row.names = FALSE)
}

##Frame of division check

##This code changes the column names so ChroMo can automatically detect each parameter.

setwd(path)
files <- list.files(path)
print(files)

sapply(files, function(file){
  
  x <- read.csv(file)
  colnames(x) <- c("frame","particle","area","x","y","XM","YM","perimeter","major","minor","Angle","circularity","frame.1","AR","Roundness","convexity")
  ##write.csv(paste0("NewNames_", file),x)
  
  x$label <- var_label
  
  
  x$particle <- strsplit(as.character(x$particle),"_R3D")[[1]][1]
  
  
  x_subset = x[,c(1,2,3,4,5,9,10,12,16,17)]
  
  
  write.csv(x_subset, file, row.names=F)
  
  
})



